### ISSUE TITLE
Isolation level bug in SQL Server

### ISSUE THREAD

**Issue by chrischu** [NEventStore/NEventStore.Persistence.SQL#17]
Unfortunately SQL Server has a bug with transaction isolation levels that could lead to invalid isolation levels being used. When getting a connection from the connection pool, the isolation level is not reset to the default (ReadCommitted) so isolation levels from previous connections can leak into new connections.

I created a rempro sample that showcases the problem (see attached files):
[NEventStoreIsolationLevelReproSample.zip](https://github.com/NEventStore/NEventStore.Persistence.SQL/files/169153/NEventStoreIsolationLevelReproSample.zip)

**Comment by chrischu** [comment]
This might be a more appropriate place for this issue than the previous one (https://github.com/NEventStore/NEventStore/issues/424)

**Comment by chrischu** [comment]
My proposed solution is to explicitly set the isolation level to the default after opening a connection. For this purpose ISqlDialect probably needs a new method that is invoked after the connection is opened, the MSqlDialect can then set the isolation level explicitly in that method.

I'll probably start working on a pull request for this idea next week (Monday). If someone has comments/other suggestions it would be cool if they could be posted over the weekend so I can take them into account :).

**Comment by chrischu** [comment]
I hope the pull request is ok, let me know if it isn't :).

**Comment by chrischu** [comment]
Btw as it turns out no new method in ISqlDialect wasn't necessary, I just used the OpenTransaction method, since this method is always used after opening the connection anyway.

**Comment by andreabalducci** [comment]
thanks, we'll review the pr next week.

**Comment by fschmied** [comment]
Workaround for 5.2.0: Subclass MsSqlDialect and override `BeginTransaction` to create a dedicated `ReadCommitted` transaction.

**Comment by chrischu** [comment]
Is there any status update regarding the review of the PR?

**Comment by AGiorgetti** [comment]
The pull request was merged
