### ISSUE TITLE
Clean up the driver from the old 'Dispatcher' code

### ISSUE THREAD

**Issue by AGiorgetti** [NEventStore/NEventStore.Persistence.SQL#26]
- [x] remove the methods:  'GetUndispatchedCommits', 'MarkCommitAsDispatched' from the ISqlDialect interface and implementation
- [x] remove the methods: 'GetUndispatchedCommits', 'MarkCommitAsDispatched' from the SqlPersistenceEngine class
- [ ] cleanup the database schemas and queries from the dispatched field references
- [x] clean the resx file from the unneeded pieces

**Comment by mariusmans** [comment]
With PollingClient2 how do we mark a Commit as Dispatched ?

**Comment by AGiorgetti** [comment]
Commits do not need to be marked as dispatched, each Polling Client will need to keep track of the last commit that it has processed.

looking at this very simple code:
https://github.com/NEventStore/NEventStore/blob/master/src/NEventStore.PollingClientExample/MainProgram.cs

you have two points in which you can save the last processed checkpoint: 
- just before the polling callback ends
- when the application ends, right before shutting down.

**Comment by mariusmans** [comment]
As I see it, it's an inconvenience having another storage facility when the database is already there. I adds another point of failure.

Also, during fault conditions, the un-dispatched events will be easier to debug and fix if all the relevant data is in the same place. 
Just me 2 cents 😊
