### ISSUE TITLE
Commit order of commits with same timestamp is random when using GetFrom/GetFromTo with a DateTime

### ISSUE THREAD

**Issue by chrischu** [NEventStore/NEventStore.Persistence.SQL#35]
Hi!

I ran into a problem with NEventStore (we're currently using NES7): when I have two commits that have the same CommitStamp the order in which they are returned when I call `IPersistStream.GetFrom(string bucketId, DateTime start)` (or the FromTo variant) is random, since they are only ordered by `CommitStamp, StreamId, CommitSequence` (see https://github.com/NEventStore/NEventStore.Persistence.SQL/blob/master/src/NEventStore.Persistence.Sql/SqlDialects/CommonSqlStatements.resx#L150).

Is there any reason for this behavior? Why are not all queries sorted by `CheckpointNumber`?

Thanks in advance!

**Comment by AGiorgetti** [comment]
I think there's no real reason to keep the old behavior, I'll check and eventually fix the queries

**Comment by drauch** [comment]
We think that the fix broke the index usage. It's still required to use `CommitStamp, CheckpointNumber` as ORDER BY clause in order that the corresponding index can be used.

**Comment by AGiorgetti** [comment]
Hi @drauch ,I think that opening a new Issue and a PR will be good, thanks!

**Comment by drauch** [comment]
=> #38
