### ISSUE TITLE
Using Microsoft.Data.SqlClient instead of System.Data.SqlClient

### ISSUE THREAD

**Issue by KlemensGenetec** [NEventStore/NEventStore.Persistence.SQL#40]
Since new feature development of System.Data.SqlClient pretty much stopped and some features like Authentication via Workload identities is already not supported, why not switch to Microsoft.Data.SqlClient?

Trying to get it to use the new version is very simple since all currently supported versions are supported by the new SqlClient. Trying to do it in the project pretty much only needed a 2 line change.

I can also create a PR for this if its something that would be acceptable.

Thanks!

**Comment by esbenbach** [comment]
Actually, we are now at a point where System.Data.SqlClient is no longer compatible with NET8.
I will create a PR for this and hope it gets some traction because we are stuck right now :(

**Comment by KlemensGenetec** [comment]
Well its still compatible and we are using it with net 8. but its lacking critical features.

**Comment by esbenbach** [comment]
Well, compatible unless you are affected by the bug i referenced in the PR :-)
We have som reflection discovery code that breaks on net8 due to system.data.sqlclient

**Comment by AGiorgetti** [comment]
Thanks @esbenbach for your PR, there's some more work to do (like updating properly the nuspec files and fixing some references here and there).
I'll start from your code and create a spike completely replacing System.Data.SqlClient with Microsoft.Data.SqlClient even for net462 to see if all tests are green.

**Comment by esbenbach** [comment]
@AGiorgetti - okay, let me know if I need to do some more on it. A complete replacement would probably be easier to maintain in the long run :)

**Comment by AGiorgetti** [comment]
I wasn't able to push new commits on yout branch, so I created another one incorporating you commits (this way our build machine can run all the tests).

Take a look at this PR: #44 .

If it's all good we can close it and release a new version.

**Comment by AGiorgetti** [comment]
closed in #44

**Comment by esbenbach** [comment]
How are changes published to NuGet - noticed there is nothing there yet, but unaware if something manual needs to be done in order for you to publish the resulting package.

**Comment by KlemensGenetec** [comment]
Unfortunately i still don't see it in the releases. Did it every complete?

**Comment by esbenbach** [comment]
Yearh its tagged, its on nuget (and working mind you), but its missing from the releases section GH. A manual step missing presumably :)

**Comment by KlemensGenetec** [comment]
oh thats amazing. finally can get rid of the old system.data.sql package completely. :)
