### ISSUE TITLE
Package Setup

### ISSUE THREAD

**Issue by andreabalducci** [NEventStore/NEventStore.Persistence.SQL#9]
with the split (https://github.com/NEventStore/NEventStore/issues/408) we need a new package configuration
- TeamCity build
- MyGet 
- NuGet

**Comment by alkampfergit** [comment]
Actually package is published to MyGet by TeamCity build, we should be able to push to nuget without problem.

**Comment by tlycken** [comment]
What's the status on publishing this package to NuGet?

In the meantime, what MyGet feed do I need to add to be able to add this package to my project?
